import tables

class GNM_Pool_Mixin(object):
    """Contains file and h5 table definitions for the GNM_Pool DataStorage.
    Versions are different enough for Pools that I'm keying everything off the
    version number."""
    DIRECT_ENUMS = ['transfer_type']

    POOLS_DEF = {'2.1':dict(cusip = (0, 9), pool_number = (9, 15), pool_indicator = (15, 16), pool_type = (16, 18),
             security_interest_rate = (19, 24), pool_issue_date = (24, 32), pool_maturity_date = (32, 40),
             original_aggregate_amount = (40, 55), issuer_number = (55, 59), issuer_name = (59, 99), security_margin = (99, 103),
             interest_adjustment_date = (103, 111), payment_adjustment_date = (111, 119), number_of_loans_in_pool = (119, 125),
             aols = (125, 135), maximum_aols_q4 = (135, 145), third_quartile_aols_q3 = (145, 155), median_aols_q2 = (155, 165),
             first_quartile_aols_q1 = (165, 175), minimum_aols_q0 = (175, 185), wac = (185, 190), maximum_wac_q4 = (190, 195),
             third_quartile_wac_q3 = (195, 200), median_wac_q2 = (200, 205), first_quartile_wac_q1 = (205, 210),
             minimum_wac_q0 = (210, 215), warm = (215, 218), maximum_warm_q4 = (218, 221), third_quartile_warm_q3 = (221, 224),
             median_warm_q2 = (224, 227), first_quartile_warm_q1 = (227, 230), minimum_warm_q0 = (230, 233), wala = (233, 236),
             maximum_wala_q4 = (236, 239), third_quartile_wala_q3 = (239, 242), median_wala_q2 = (242, 245),
             first_quartile_wala_q1 = (245, 248), minimum_wala_q0 = (248, 251), waolt = (251, 254), maximum_waolt_q4 = (254, 257),
             third_quartile_waolt_q3 = (257, 260), median_waolt_q2 = (260, 263), first_quartile_waolt_q1 = (263, 266),
             minimum_waolt_q0 = (266, 269), wagm = (269, 274), maximum_wagm_q4 = (274, 279), third_quartile_wagm_q3 = (279, 284),
             median_wagm_q2 = (284, 289), first_quartile_wagm_q1 = (289, 294), minimum_wagm_q0 = (294, 299),
             weighted_average_original_ltv = (299, 302), maximum_ltv_q4 = (302, 305), third_quartile_ltv_q3 = (305, 308),
             median_ltv_q2 = (308, 311), first_quartile_ltv_q1 = (311, 314), minimum_ltv_q0 = (314, 317),
             ltv_not_available_number_of_loans = (317, 323), ltv_not_available_upb = (323, 336),
             ltv_not_available_pct_of_upb = (336, 341), purchase_number_of_loans = (341, 347), purchase_upb = (347, 360),
             purchase_pct_of_upb = (360, 365), refinance_number_of_loans = (365, 371), refinance_upb = (371, 384),
             refinance_pct_of_upb = (384, 389), hamp_modified_number_of_loans = (389, 395), hamp_modified_upb = (395, 408),
             hamp_modified_pct_of_total_upb = (408, 413), non_hamp_modified_number_of_loans = (413, 419),
             non_hamp_modified_upb = (419, 432), non_hamp_modified_pct_of_total_upb = (432, 437),
             loan_purpose_not_available_number_of_loans = (437, 443), loan_purpose_not_available_upb = (443, 456),
             loan_purpose_not_available_pct_of_upb = (456, 461), weighted_average_original_cltv = (461, 464),
             maximum_cltv_q4 = (464, 467), third_quartile_cltv_q3 = (467, 470), median_cltv_q2 = (470, 473),
             first_quartile_cltv_q1 = (473, 476), minimum_cltv_q0 = (476, 479), weighted_average_original_loan_size = (479, 489),
             look_back_period = (489, 490), one_unit_number_of_loans = (533, 539), one_unit_upb = (539, 552),
             one_unit_pct_of_upb = (552, 557), few_units_number_of_loans = (557, 563), few_units_upb = (563, 576),
             few_units_pct_of_upb = (576, 581), ptna_number_of_loans = (581, 587), ptna_upb = (587, 600),
             ptna_pct_of_upb = (600, 605), pool_upb = (605, 620), as_of_date = (629, 635)),
                 '1.3':dict(cusip = (0, 9), pool_number = (9, 15), pool_indicator = (15, 16), pool_type = (16, 18), security_interest_rate = (19, 24), pool_issue_date = (24, 32), pool_maturity_date = (32, 40), original_aggregate_amount = (40, 55), issuer_number = (55, 59), issuer_name = (59, 99), security_margin = (99, 103), interest_adjustment_date = (103, 111), payment_adjustment_date = (111, 119), number_of_loans_in_pool = (119, 125), aols = (125, 133), maximum_aols_q4 = (133, 141), third_quartile_aols_q3 = (141, 149), median_aols_q2 = (149, 157), first_quartile_aols_q1 = (157, 165), minimum_aols_q0 = (165, 173), wac = (173, 178), maximum_wac_q4 = (178, 183), third_quartile_wac_q3 = (183, 188), median_wac_q2 = (188, 193), first_quartile_wac_q1 = (193, 198), minimum_wac_q0 = (198, 203), warm = (203, 206), maximum_warm_q4 = (206, 209), third_quartile_warm_q3 = (209, 212), median_warm_q2 = (212, 215), first_quartile_warm_q1 = (215, 218), minimum_warm_q0 = (218, 221), wala = (221, 224), maximum_wala_q4 = (224, 227), third_quartile_wala_q3 = (227, 230), median_wala_q2 = (230, 233), first_quartile_wala_q1 = (233, 236), minimum_wala_q0 = (236, 239), waolt = (239, 242), maximum_waolt_q4 = (242, 245), third_quartile_waolt_q3 = (245, 248), median_waolt_q2 = (248, 251), first_quartile_waolt_q1 = (251, 254), minimum_waolt_q0 = (254, 257), wagm = (257, 262), maximum_wagm_q4 = (262, 267), third_quartile_wagm_q3 = (267, 272), median_wagm_q2 = (272, 277), first_quartile_wagm_q1 = (277, 282), minimum_wagm_q0 = (282, 287), weighted_average_original_ltv = (287, 290), maximum_ltv_q4 = (290, 293), third_quartile_ltv_q3 = (293, 296), median_ltv_q2 = (296, 299), first_quartile_ltv_q1 = (299, 302), minimum_ltv_q0 = (302, 305), ltv_not_available_number_of_loans = (305, 311), ltv_not_available_upb = (311, 324), ltv_not_available_pct_of_upb = (324, 329), purchase_number_of_loans = (329, 335), purchase_upb = (335, 348), purchase_pct_of_upb = (348, 353), refinance_number_of_loans = (353, 359), refinance_upb = (359, 372), refinance_pct_of_upb = (372, 377), hamp_modified_number_of_loans = (377, 383), hamp_modified_upb = (383, 396), hamp_modified_pct_of_total_upb = (396, 401), non_hamp_modified_number_of_loans = (401, 407), non_hamp_modified_upb = (407, 420), non_hamp_modified_pct_of_total_upb = (420, 425), loan_purpose_not_available_number_of_loans = (425, 431), loan_purpose_not_available_upb = (431, 444), loan_purpose_not_available_pct_of_upb = (444, 449), weighted_average_original_cltv = (449, 452), maximum_cltv_q4 = (452, 455), third_quartile_cltv_q3 = (455, 458), median_cltv_q2 = (458, 461), first_quartile_cltv_q1 = (461, 464), minimum_cltv_q0 = (464, 467), weighted_average_original_loan_size = (467, 475), look_back_period = (475, 476), one_unit_number_of_loans = (533, 539), one_unit_upb = (539, 552), one_unit_pct_of_upb = (552, 557), few_units_number_of_loans = (557, 563), few_units_upb = (563, 576), few_units_pct_of_upb = (576, 581), ptna_number_of_loans = (581, 587), ptna_upb = (587, 600), ptna_pct_of_upb = (600, 605), pool_upb = (605, 620), as_of_date = (629, 635))}

    MULTIISSUERS_DEF = {'2.1':{'as_of_date': (87, 93), 'cusip': (0, 9), 'issuer_name': (23, 63), 'issuer_number': (19, 23), 'issuers_pct_of_pool': (82, 87), 'issuers_upb': (69, 82), 'number_of_loans': (63, 69), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18)}}

    YEARS_DEF = {'2.1':{'as_of_date': (184, 190), 'cusip': (0, 9), 'num_loans_foy_1': (41, 47), 'num_loans_foy_2': (74, 80), 'num_loans_foy_3': (107, 113), 'num_loans_foy_4': (140, 146), 'num_loans_foy_others': (173, 179), 'origin_yr_1': (19, 23), 'origin_yr_2': (52, 56), 'origin_yr_3': (85, 89), 'origin_yr_4': (118, 122), 'origin_yr_others': (151, 155), 'pct_loans_foy_1': (47, 52), 'pct_loans_foy_2': (80, 85), 'pct_loans_foy_3': (113, 118), 'pct_loans_foy_4': (146, 151), 'pct_loans_foy_others': (179, 184), 'pct_upb_foy_1': (36, 41), 'pct_upb_foy_2': (69, 74), 'pct_upb_foy_3': (102, 107), 'pct_upb_foy_4': (135, 140), 'pct_upb_foy_others': (168, 173), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'upb_foy_1': (23, 36), 'upb_foy_2': (56, 69), 'upb_foy_3': (89, 102), 'upb_foy_4': (122, 135), 'upb_foy_others': (155, 168)}}

    MSAS_DEF = {'2.1':{'as_of_date': (337, 343), 'cusip': (0, 9), 'eighth_msa': (226, 231), 'eighth_number_loans': (231, 237), 'eighth_pct_upb': (250, 255), 'eighth_upb_loans': (237, 250), 'fifth_msa': (139, 144), 'fifth_number_loans': (144, 150), 'fifth_pct_upb': (163, 168), 'fifth_upb_loans': (150, 163), 'first_msa': (23, 28), 'first_number_loans': (28, 34), 'first_pct_upb': (47, 52), 'first_upb_loans': (34, 47), 'fourth_msa': (110, 115), 'fourth_number_loans': (115, 121), 'fourth_pct_upb': (134, 139), 'fourth_upb_loans': (121, 134), 'issuer': (19, 23), 'ninth_msa': (255, 260), 'ninth_number_loans': (260, 266), 'ninth_pct_upb': (279, 284), 'ninth_upb_loans': (266, 279), 'no_msa_number_loans': (313, 319), 'no_msa_pct_upb': (332, 337), 'no_msa_upb_loans': (319, 332), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'second_msa': (52, 57), 'second_number_loans': (57, 63), 'second_pct_upb': (76, 81), 'second_upb_loans': (63, 76), 'seventh_msa': (197, 202), 'seventh_number_loans': (202, 208), 'seventh_pct_upb': (221, 226), 'seventh_upb_loans': (208, 221), 'sixth_msa': (168, 173), 'sixth_number_loans': (173, 179), 'sixth_pct_upb': (192, 197), 'sixth_upb_loans': (179, 192), 'tenth_msa': (284, 289), 'tenth_number_loans': (289, 295), 'tenth_pct_upb': (308, 313), 'tenth_upb_loans': (295, 308), 'third_msa': (81, 86), 'third_number_loans': (86, 92), 'third_pct_upb': (105, 110), 'third_upb_loans': (92, 105)}}

    PREMODIFICATIONS_DEF = {'2.1':{'as_of_date': (159, 165), 'avg_lad': (23, 26), 'cusip': (0, 9), 'first_quartile_lad_q1': (35, 38), 'first_quartile_premodified_ols_q1': (110, 120), 'issuer': (19, 23), 'max_premodified_ols_q4': (80, 90), 'maximum_lad_q4': (26, 29), 'median_lad_q2': (32, 35), 'median_premodified_ols_q2': (100, 110), 'min_lad_q0': (38, 41), 'min_premodified_ols_q0': (120, 130), 'num_loans': (59, 65), 'num_loans_premodified_opb': (148, 154), 'pct_of_pool': (65, 70), 'pct_of_pool_premodified_opb': (154, 159), 'pct_of_pool_upb': (54, 59), 'pct_of_pool_upb_premodified_opb': (143, 148), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'premodified_ols': (70, 80), 'third_quartile_lad_q3': (29, 32), 'third_quartile_premodified_ols_q3': (90, 100), 'upb_for_premodified_loans': (41, 54), 'upb_premodified_opb': (130, 143)},
                            '1.3':{'as_of_date': (147, 153), 'avg_lad': (23, 26), 'cusip': (0, 9), 'first_quartile_lad_q1': (35, 38), 'first_quartile_premodified_ols_q1': (102, 110), 'issuer': (19, 23), 'max_premodified_ols_q4': (78, 86), 'maximum_lad_q4': (26, 29), 'median_lad_q2': (32, 35), 'median_premodified_ols_q2': (94, 102), 'min_lad_q0': (38, 41), 'min_premodified_ols_q0': (111, 118), 'num_loans': (59, 65), 'num_loans_premodified_opb': (136, 142), 'pct_of_pool': (65, 70), 'pct_of_pool_premodified_opb': (131, 136), 'pct_of_pool_upb': (54, 59), 'pct_of_pool_upb_premodified_opb': (142, 147), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'premodified_ols': (70, 78), 'third_quartile_lad_q3': (29, 32), 'third_quartile_premodified_ols_q3': (86, 94), 'upb_for_premodified_loans': (41, 54), 'upb_premodified_opb': (118, 131)}}

    REMOVALS_DEF = {'2.1':{'as_of_date': (167, 173), 'cusip': (0, 9), 'foreclosure_claim_payment_num_loans': (71, 77), 'foreclosure_claim_payment_pct_upb': (90, 95), 'foreclosure_claim_payment_upb': (77, 90), 'issuer': (19, 23), 'mortgagor_payoff_num_loans': (23, 29), 'mortgagor_payoff_pct_upb': (42, 47), 'mortgagor_payoff_upb': (29, 42), 'other_removal_num_loans': (143, 149), 'other_removal_number_of_pct_upb': (162, 167), 'other_removal_upb': (149, 162), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'repurchase_delinquent_loan_num_loans': (47, 53), 'repurchase_delinquent_loan_pct_upb': (66, 71), 'repurchase_delinquent_loan_upb': (53, 66), 'repurchase_loss_mitigation_num_loans': (95, 101), 'repurchase_loss_mitigation_pct_upb': (114, 119), 'repurchase_loss_mitigation_upb': (101, 114), 'substitution_num_loans': (119, 125), 'substitution_number_of_pct_upb': (138, 143), 'substitution_upb': (125, 138)}}

    STATES_DEF = {'2.1':{'as_of_date': (69, 75), 'balance_pct': (34, 39), 'current_security_balance_state': (21, 34), 'cusip': (0, 9), 'num_loans_pct': (45, 50), 'num_loans_state': (39, 45), 'original_balance_state': (56, 69), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'state': (19, 21), 'total_loans': (50, 56)}}

    VARIOUSES_DEF = {'2.1':{'as_of_date':(883, 889), 'cusip': (0, 9), 'fha_num_loans': (37, 43), 'fha_num_loans_30_days_delinquent': (547, 553), 'fha_num_loans_60_days_delinquent': (571, 577), 'fha_num_loans_90_days_delinquent': (595, 601), 'fha_num_loans_pct_total_loans': (43, 48), 'fha_original_pool_balance': (48, 61), 'fha_pct_upb_of_loans_30_days_delinquent': (566, 571), 'fha_pct_upb_of_loans_60_days_delinquent': (590, 595), 'fha_pct_upb_of_loans_90_days_delinquent': (614, 619), 'fha_pool_upb': (19, 32), 'fha_upb_of_loans_30_days_delinquent': (553, 566), 'fha_upb_of_loans_60_days_delinquent': (577, 590), 'fha_upb_of_loans_90_days_delinquent': (601, 614), 'fha_upb_pct_total_pool': (32, 37), 'num_loans_30_days_delinquent': (475, 481), 'num_loans_60_days_delinquent': (499, 505), 'num_loans_90_days_delinquent': (523, 529), 'num_loans_foreclosed_with_claim_payment': (235, 241), 'num_loans_paid_off': (187, 193), 'number_of_fha_buydown_loans': (331, 337), 'number_of_other_removal_repurchased_loans': (307, 313), 'number_of_repurchased_delinquent_loans': (211, 217), 'number_of_repurchased_loss_mitigation_loans': (259, 265), 'number_of_repurchased_substitution_loans': (283, 289), 'number_of_va_buydown_loans': (355, 361), 'pct_upb_of_fha_buydown_loans': (350, 355), 'pct_upb_of_loans_30_days_delinquent': (494, 499), 'pct_upb_of_loans_60_days_delinquent': (518, 523), 'pct_upb_of_loans_90_days_delinquent': (542, 547), 'pct_upb_of_loans_foreclosed_with_claim_payment': (254, 259), 'pct_upb_of_loans_paid_off': (206, 211), 'pct_upb_of_other_removal_repurchased_loans': (326, 331), 'pct_upb_of_repurchased_delinquent_loans': (230, 235), 'pct_upb_of_repurchased_loss_mitigation_loans': (278, 283), 'pct_upb_of_repurchased_substitution_loans': (302, 307), 'pct_upb_of_va_buydown_loans': (374, 379), 'pih_num_loans': (163, 169), 'pih_num_loans_30_days_delinquent': (763, 769), 'pih_num_loans_60_days_delinquent': (787, 793), 'pih_num_loans_90_days_delinquent': (811, 817), 'pih_num_loans_pct_total_loans': (169, 174), 'pih_original_pool_balance': (174, 187), 'pih_pct_upb_of_loans_30_days_delinquent': (782, 787), 'pih_pct_upb_of_loans_60_days_delinquent': (806, 811), 'pih_pct_upb_of_loans_60_days_delinquent': (830, 835), 'pih_pool_upb': (145, 158), 'pih_upb_of_loans_30_days_delinquent': (769, 782), 'pih_upb_of_loans_60_days_delinquent': (793, 806), 'pih_upb_of_loans_90_days_delinquent': (817, 830), 'pih_upb_pct_total_pool': (158, 163), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'rd_num_loans': (121, 127), 'rd_num_loans_30_days_delinquent': (691, 697), 'rd_num_loans_60_days_delinquent': (715, 721), 'rd_num_loans_90_days_delinquent': (739, 745), 'rd_num_loans_pct_total_loans': (127, 132), 'rd_original_pool_balance': (132, 145), 'rd_pct_upb_of_loans_30_days_delinquent': (710, 715), 'rd_pct_upb_of_loans_60_days_delinquent': (734, 739), 'rd_pct_upb_of_loans_60_days_delinquent': (758, 769), 'rd_pool_upb': (103, 116), 'rd_upb_of_loans_30_days_delinquent': (697, 710), 'rd_upb_of_loans_60_days_delinquent': (721, 734), 'rd_upb_of_loans_90_days_delinquent': (745, 758), 'rd_upb_pct_total_pool': (116, 121), 'unpaid_principal_balance_of_loans_paid_off': (193, 206), 'upb_of_fha_buydown_loans': (337, 350), 'upb_of_loans_30_days_delinquent': (481, 494), 'upb_of_loans_60_days_delinquent': (505, 518), 'upb_of_loans_90_days_delinquent': (529, 542), 'upb_of_loans_foreclosed_with_claim_payment': (241, 254), 'upb_of_other_removal_repurchased_loans': (313, 326), 'upb_of_repurchased_delinquent_loans': (217, 230), 'upb_of_repurchased_loss_mitigation_loans': (265, 278), 'upb_of_repurchased_substitution_loans': (289, 302), 'upb_of_va_buydown_loans': (361, 374), 'va_num_loans': (79, 85), 'va_num_loans_30_days_delinquent': (619, 625), 'va_num_loans_60_days_delinquent': (643, 649), 'va_num_loans_90_days_delinquent': (667, 673), 'va_num_loans_pct_total_loans': (85, 90), 'va_original_pool_balance': (90, 103), 'va_pct_upb_of_loans_30_days_delinquent': (638, 643), 'va_pct_upb_of_loans_60_days_delinquent': (662, 667), 'va_pct_upb_of_loans_90_days_delinquent': (686, 691), 'va_pool_upb': (61, 74), 'va_upb_of_loans_30_days_delinquent': (625, 638), 'va_upb_of_loans_60_days_delinquent': (649, 662), 'va_upb_of_loans_90_days_delinquent': (673, 686), 'va_upb_pct_total_pool': (74, 79)}}

    SUPPLEMENTALS_DEF = {'2.1':{'as_of_date': (761, 767), 'cash_out_refi_num_loans': (665, 671), 'cash_out_refi_pct_upb': (684, 689), 'cash_out_refi_upb': (671, 684), 'credit_score_not_available_num_loans': (41, 47), 'credit_score_not_available_pct_upb': (60, 65), 'credit_score_not_available_upb': (47, 60), 'cusip': (0, 9), 'debt_income_ratio_not_available_num_loans': (89, 95), 'debt_income_ratio_not_available_pct_upb': (108, 113), 'debt_income_ratio_not_available_upb': (95, 108), 'down_payment_assistance_num_loans': (113, 119), 'down_payment_assistance_pct_upb': (132, 137), 'down_payment_assistance_upb': (119, 132), 'fha_hamp_modified_num_loans': (209, 215), 'fha_hamp_modified_pct_upb': (228, 233), 'fha_hamp_modified_upb': (215, 228), 'fha_nonhamp_modified_num_loans': (233, 239), 'fha_nonhamp_modified_pct_upb': (252, 257), 'fha_nonhamp_modified_upb': (239, 252), 'fha_purchase_num_loans': (161, 167), 'fha_purchase_pct_upb': (180, 185), 'fha_purchase_upb': (167, 180), 'fha_purpose_not_available_num_loans': (257, 263), 'fha_purpose_not_available_pct_upb': (276, 281), 'fha_purpose_not_available_upb': (263, 276), 'fha_refinance_num_loans': (185, 191), 'fha_refinance_pct_upb': (204, 209), 'fha_refinance_upb': (191, 204), 'fha_short_refinance_num_loans': (713, 719), 'fha_short_refinance_pct_upb': (732, 737), 'fha_short_refinance_upb': (719, 732), 'first_quartile_credit_score_q1': (35, 38), 'first_quartile_debt_income_ratio_q1': (81, 85), 'issuer': (19, 23), 'maximum_credit_score_q4': (26, 29), 'maximum_debt_income_ratio_q4': (69, 73), 'median_credit_score_q2': (32, 35), 'median_debt_income_ratio_q2': (77, 81), 'minimum_credit_score_q0': (38, 41), 'minimum_debt_income_ratio_q0': (85, 89), 'non_streamlined_refi_num_loans': (641, 647), 'non_streamlined_refi_purchase_pct_upb': (660, 665), 'non_streamlined_refi_purchase_upb': (647, 660), 'pih_hamp_modified_num_loans': (449, 455), 'pih_hamp_modified_pct_upb': (468, 473), 'pih_hamp_modified_upb': (455, 468), 'pih_nonhamp_modified_num_loans': (473, 479), 'pih_nonhamp_modified_pct_upb': (492, 497), 'pih_nonhamp_modified_upb': (479, 492), 'pih_purchase_num_loans': (401, 407), 'pih_purchase_pct_upb': (420, 425), 'pih_purchase_upb': (407, 420), 'pih_purpose_not_available_num_loans': (497, 503), 'pih_purpose_not_available_pct_upb': (516, 521), 'pih_purpose_not_available_upb': (503, 516), 'pih_refinance_num_loans': (425, 431), 'pih_refinance_pct_upb': (444, 449), 'pih_refinance_upb': (431, 444), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'rd_hamp_modified_num_loans': (569, 575), 'rd_hamp_modified_pct_upb': (588, 593), 'rd_hamp_modified_upb': (575, 588), 'rd_nonhamp_modified_num_loans': (593, 599), 'rd_nonhamp_modified_pct_upb': (612, 617), 'rd_nonhamp_modified_upb': (599, 612), 'rd_purchase_num_loans': (521, 527), 'rd_purchase_pct_upb': (540, 545), 'rd_purchase_upb': (527, 540), 'rd_purpose_not_available_num_loans': (617, 623), 'rd_purpose_not_available_pct_upb': (636, 641), 'rd_purpose_not_available_upb': (623, 636), 'rd_refinance_num_loans': (545, 551), 'rd_refinance_pct_upb': (564, 569), 'rd_refinance_upb': (551, 564), 'refinance_type_not_available_num_loans': (737, 743), 'refinance_type_not_available_pct_upb': (756, 761), 'refinance_type_not_available_upb': (743, 756), 'streamlined_refi_num_loans': (689, 695), 'streamlined_refi_pct_upb': (708, 713), 'streamlined_refi_upb': (695, 708), 'third_quartile_credit_score_q3': (29, 32), 'third_quartile_debt_income_ratio_q3': (73, 77), 'va_hamp_modified_num_loans': (329, 335), 'va_hamp_modified_pct_upb': (348, 353), 'va_hamp_modified_upb': (335, 348), 'va_nonhamp_modified_num_loans': (353, 359), 'va_nonhamp_modified_pct_upb': (372, 377), 'va_nonhamp_modified_upb': (359, 372), 'va_purchase_num_loans': (281, 287), 'va_purchase_pct_upb': (300, 305), 'va_purchase_upb': (287, 300), 'va_purpose_not_available_num_loans': (377, 383), 'va_purpose_not_available_pct_upb': (396, 401), 'va_purpose_not_available_upb': (383, 396), 'va_refinance_num_loans': (305, 311), 'va_refinance_pct_upb': (324, 329), 'va_refinance_upb': (311, 324), 'weighted_average_credit_score': (23, 26), 'weighted_average_debt_income_ratio': (65, 69), 'without_payment_assistance_num_loans': (137, 143), 'without_payment_assistance_pct_upb': (156, 161), 'without_payment_assistance_upb': (143, 156)}}

    MULTIISSUERDELIQUENCIES_DEF = {'2.1':{'as_of_date': (383, 389), 'cusip': (0, 9), 'fha_num_loans_ninety_days_delinquent': (143, 149), 'fha_num_loans_sixty_days_delinquent': (119, 125), 'fha_num_loans_thirty_days_delinquent': (95, 101), 'fha_pct_upb_ninety_days_delinquent': (162, 167), 'fha_pct_upb_sixty_days_delinquent': (138, 143), 'fha_pct_upb_thirty_days_delinquent': (114, 119), 'fha_upb_ninety_days_delinquent': (149, 162), 'fha_upb_sixty_days_delinquent': (125, 138), 'fha_upb_thirty_days_delinquent': (101, 114), 'issuer': (19, 23), 'num_loans_ninety_days_delinquent': (71, 77), 'num_loans_sixty_days_delinquent': (47, 53), 'num_loans_thirty_days_delinquent': (23, 29), 'pct_upb_ninety_days_delinquent': (90, 95), 'pct_upb_sixty_days_delinquent': (66, 71), 'pct_upb_thirty_days_delinquent': (42, 47), 'pih_num_loans_ninety_days_delinquent': (359, 365), 'pih_num_loans_sixty_days_delinquent': (335, 341), 'pih_num_loans_thirty_days_delinquent': (311, 317), 'pih_pct_upb_ninety_days_delinquent': (378, 383), 'pih_pct_upb_sixty_days_delinquent': (354, 359), 'pih_pct_upb_thirty_days_delinquent': (330, 335), 'pih_upb_ninety_days_delinquent': (365, 378), 'pih_upb_sixty_days_delinquent': (341, 354), 'pih_upb_thirty_days_delinquent': (317, 330), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'rd_num_loans_ninety_days_delinquent': (287, 293), 'rd_num_loans_sixty_days_delinquent': (263, 269), 'rd_num_loans_thirty_days_delinquent': (239, 245), 'rd_pct_upb_ninety_days_delinquent': (306, 311), 'rd_pct_upb_sixty_days_delinquent': (282, 287), 'rd_pct_upb_thirty_days_delinquent': (258, 263), 'rd_upb_ninety_days_delinquent': (293, 306), 'rd_upb_sixty_days_delinquent': (269, 282), 'rd_upb_thirty_days_delinquent': (245, 258), 'upb_ninety_days_delinquent': (77, 90), 'upb_sixty_days_delinquent': (53, 66), 'upb_thirty_days_delinquent': (29, 42), 'va_num_loans_ninety_days_delinquent': (215, 221), 'va_num_loans_sixty_days_delinquent': (191, 197), 'va_num_loans_thirty_days_delinquent': (167, 173), 'va_pct_upb_ninety_days_delinquent': (234, 239), 'va_pct_upb_sixty_days_delinquent': (210, 215), 'va_pct_upb_thirty_days_delinquent': (186, 191), 'va_upb_ninety_days_delinquent': (221, 234), 'va_upb_sixty_days_delinquent': (197, 210), 'va_upb_thirty_days_delinquent': (173, 186)}}

    INSURANCEPREMIUMS_DEF = {'2.1':{'annual_mip_000_num_loans': (791, 797), 'annual_mip_000_pct_upb': (810, 815), 'annual_mip_000_upb': (797, 810), 'annual_mip_110_num_loans': (359, 365), 'annual_mip_110_pct_upb': (378, 383), 'annual_mip_110_upb': (365, 378), 'annual_mip_115_num_loans': (383, 389), 'annual_mip_115_pct_upb': (402, 407), 'annual_mip_115_upb': (389, 402), 'annual_mip_120_num_loans': (407, 413), 'annual_mip_120_pct_upb': (426, 431), 'annual_mip_120_upb': (413, 426), 'annual_mip_125_num_loans': (431, 437), 'annual_mip_125_pct_upb': (450, 455), 'annual_mip_125_upb': (437, 450), 'annual_mip_145_num_loans': (455, 461), 'annual_mip_145_pct_upb': (474, 479), 'annual_mip_145_upb': (461, 474), 'annual_mip_150_num_loans': (479, 485), 'annual_mip_150_pct_upb': (498, 503), 'annual_mip_150_upb': (485, 498), 'annual_mip_25_num_loans': (191, 197), 'annual_mip_25_pct_upb': (210, 215), 'annual_mip_25_upb': (197, 210), 'annual_mip_35_num_loans': (215, 221), 'annual_mip_35_pct_upb': (234, 239), 'annual_mip_35_upb': (221, 234), 'annual_mip_50_num_loans': (239, 245), 'annual_mip_50_pct_upb': (258, 263), 'annual_mip_50_upb': (245, 258), 'annual_mip_55_num_loans': (263, 269), 'annual_mip_55_pct_upb': (282, 287), 'annual_mip_55_upb': (269, 282), 'annual_mip_60_num_loans': (287, 293), 'annual_mip_60_pct_upb': (306, 311), 'annual_mip_60_upb': (293, 306), 'annual_mip_85_num_loans': (311, 317), 'annual_mip_85_pct_upb': (330, 335), 'annual_mip_85_upb': (317, 330), 'annual_mip_90_num_loans': (335, 341), 'annual_mip_90_pct_upb': (354, 359), 'annual_mip_90_upb': (341, 354), 'annual_mip_NA_num_loans': (503, 509), 'annual_mip_NA_pct_upb': (522, 527), 'annual_mip_NA_upb': (509, 522), 'as_of_date': (1463, 1469), 'broker_num_loans': (599, 605), 'broker_pct_upb': (618, 623), 'broker_upb': (605, 618), 'correspondent_num_loans': (623, 629), 'correspondent_pct_upb': (642, 647), 'correspondent_upb': (629, 642), 'cusip': (0, 9), 'first_time_homebuyer_NA_num_loans': (575, 581), 'first_time_homebuyer_NA_pct_upb': (594, 599), 'first_time_homebuyer_NA_upb': (581, 594), 'first_time_homebuyer_num_loans': (527, 533), 'first_time_homebuyer_pct_upb': (546, 551), 'first_time_homebuyer_upb': (533, 546), 'issuer': (19, 23), 'mip_001_num_loans': (719, 725), 'mip_001_pct_upb': (738, 743), 'mip_001_upb': (725, 738), 'mip_100_num_loans': (1103, 1109), 'mip_100_pct_upb': (1122, 1127), 'mip_100_upb': (1109, 1122), 'mip_105_num_loans': (1127, 1133), 'mip_105_pct_upb': (1146, 1151), 'mip_105_upb': (1133, 1146), 'mip_130_num_loans': (911, 917), 'mip_130_pct_upb': (930, 935), 'mip_130_upb': (917, 930), 'mip_135_num_loans': (935, 941), 'mip_135_pct_upb': (954, 959), 'mip_135_upb': (941, 954), 'mip_155_num_loans': (959, 965), 'mip_155_pct_upb': (978, 983), 'mip_155_upb': (965, 978), 'mip_240_num_loans': (1007, 1013), 'mip_240_pct_upb': (1026, 1031), 'mip_240_upb': (1013, 1026), 'mip_250_num_loans': (1031, 1037), 'mip_250_pct_upb': (1050, 1055), 'mip_250_upb': (1037, 1050), 'mip_300_num_loans': (743, 749), 'mip_300_pct_upb': (762, 767), 'mip_300_upb': (749, 762), 'mip_380_num_loans': (767, 773), 'mip_380_pct_upb': (786, 791), 'mip_380_upb': (773, 786), 'mip_45_num_loans': (839, 845), 'mip_45_pct_upb': (858, 863), 'mip_45_upb': (845, 858), 'mip_50_num_loans': (983, 989), 'mip_50_pct_upb': (1002, 1007), 'mip_50_upb': (989, 1002), 'mip_70_num_loans': (863, 869), 'mip_70_pct_upb': (882, 887), 'mip_70_upb': (869, 882), 'mip_75_num_loans': (1055, 1061), 'mip_75_pct_upb': (1074, 1079), 'mip_75_upb': (1061, 1074), 'mip_80_num_loans': (1079, 1085), 'mip_80_pct_upb': (1098, 1103), 'mip_80_upb': (1085, 1098), 'mip_95_num_loans': (887, 893), 'mip_95_pct_upb': (906, 911), 'mip_95_upb': (893, 906), 'mip_other_num_loans': (815, 821), 'mip_other_pct_upb': (834, 839), 'mip_other_upb': (821, 834), 'not_first_time_homebuyer_num_loans': (551, 557), 'not_first_time_homebuyer_pct_upb': (570, 575), 'not_first_time_homebuyer_upb': (557, 570), 'origination_type_NA_num_loans': (671, 677), 'origination_type_NA_pct_upb': (690, 695), 'origination_type_NA_upb': (677, 690), 'pool_indicator': (15, 16), 'pool_number': (9, 15), 'pool_type': (16, 18), 'retail_num_loans': (647, 653), 'retail_pct_upb': (666, 671), 'retail_upb': (653, 666), 'upfront_mip_000_num_loans': (695, 701), 'upfront_mip_000_pct_upb': (714, 719), 'upfront_mip_000_upb': (701, 714), 'upfront_mip_100_num_loans': (23, 29), 'upfront_mip_100_pct_upb': (42, 47), 'upfront_mip_100_upb': (29, 42), 'upfront_mip_125_num_loans': (47, 53), 'upfront_mip_125_pct_upb': (66, 71), 'upfront_mip_125_upb': (53, 66), 'upfront_mip_150_num_loans': (71, 77), 'upfront_mip_150_pct_upb': (90, 95), 'upfront_mip_150_upb': (77, 90), 'upfront_mip_175_num_loans': (95, 101), 'upfront_mip_175_pct_upb': (114, 119), 'upfront_mip_175_upb': (101, 114), 'upfront_mip_200_num_loans': (119, 125), 'upfront_mip_200_pct_upb': (138, 143), 'upfront_mip_200_upb': (125, 138), 'upfront_mip_225_num_loans': (143, 149), 'upfront_mip_225_pct_upb': (162, 167), 'upfront_mip_225_upb': (149, 162), 'upfront_mip_NA_num_loans': (167, 173), 'upfront_mip_NA_pct_upb': (186, 191), 'upfront_mip_NA_upb': (173, 186)}}

    TRANSFERACTIVITIES_DEF = {'2.1':{'as_of_date': (55, 61), 'buying_issuer': (32, 36), 'cusip': (0, 9), 'num_loans_transferred': (36, 42), 'pool_indicator': (15, 16), 'pool_issue_date': (19, 27), 'pool_number': (9, 15), 'pool_type': (16, 18), 'selling_issuer': (28, 32), 'transfer_type': (27, 28), 'upb_transferred': (42, 55)}}

    class Pools(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        security_interest_rate = tables.Int32Col()
        pool_issue_date = tables.Time32Col()
        pool_maturity_date = tables.Time32Col()
        original_aggregate_amount = tables.Int64Col()
        issuer_number = tables.Int16Col()
        issuer_name = tables.StringCol(40)
        security_margin  = tables.Int16Col()
        interest_adjustment_date  = tables.Time32Col()
        payment_adjustment_date  = tables.Time32Col()
        number_of_loans_in_pool = tables.Int32Col()
        aols = tables.Int64Col()
        maximum_aols_q4 = tables.Int64Col()
        third_quartile_aols_q3 = tables.Int64Col()
        median_aols_q2 = tables.Int64Col()
        first_quartile_aols_q1 = tables.Int64Col()
        minimum_aols_q0 = tables.Int64Col()
        wac = tables.Int32Col()
        maximum_wac_q4 = tables.Int32Col()
        third_quartile_wac_q3 = tables.Int32Col()
        median_wac_q2 = tables.Int32Col()
        first_quartile_wac_q1 = tables.Int32Col()
        minimum_wac_q0 = tables.Int32Col()
        warm = tables.Int16Col()
        maximum_warm_q4 = tables.Int16Col()
        third_quartile_warm_q3 = tables.Int16Col()
        median_warm_q2 = tables.Int16Col()
        first_quartile_warm_q1 = tables.Int16Col()
        minimum_warm_q0 = tables.Int16Col()
        wala = tables.Int16Col()
        maximum_wala_q4 = tables.Int16Col()
        third_quartile_wala_q3 = tables.Int16Col()
        median_wala_q2 = tables.Int16Col()
        first_quartile_wala_q1 = tables.Int16Col()
        minimum_wala_q0 = tables.Int16Col()
        waolt = tables.Int16Col()
        maximum_waolt_q4 = tables.Int16Col()
        third_quartile_waolt_q3 = tables.Int16Col()
        median_waolt_q2 = tables.Int16Col()
        first_quartile_waolt_q1 = tables.Int16Col()
        minimum_waolt_q0 = tables.Int16Col()
        wagm = tables.Int32Col()
        maximum_wagm_q4 = tables.Int32Col()
        third_quartile_wagm_q3 = tables.Int32Col()
        median_wagm_q2 = tables.Int32Col()
        first_quartile_wagm_q1 = tables.Int32Col()
        minimum_wagm_q0 = tables.Int32Col()
        weighted_average_original_ltv = tables.Int16Col()
        maximum_ltv_q4 = tables.Int16Col()
        third_quartile_ltv_q3 = tables.Int16Col()
        median_ltv_q2 = tables.Int16Col()
        first_quartile_ltv_q1 = tables.Int16Col()
        minimum_ltv_q0 = tables.Int16Col()
        ltv_not_available_number_of_loans = tables.Int32Col()
        ltv_not_available_upb = tables.Int64Col()
        ltv_not_available_pct_of_upb = tables.Int32Col()
        purchase_number_of_loans = tables.Int32Col()
        purchase_upb = tables.Int64Col()
        purchase_pct_of_upb = tables.Int32Col()
        refinance_number_of_loans = tables.Int32Col()
        refinance_upb = tables.Int64Col()
        refinance_pct_of_upb = tables.Int32Col()
        hamp_modified_number_of_loans = tables.Int32Col()
        hamp_modified_upb = tables.Int64Col()
        hamp_modified_pct_of_total_upb = tables.Int32Col()
        non_hamp_modified_number_of_loans = tables.Int32Col()
        non_hamp_modified_upb = tables.Int64Col()
        non_hamp_modified_pct_of_total_upb = tables.Int32Col()
        loan_purpose_not_available_number_of_loans = tables.Int32Col()
        loan_purpose_not_available_upb = tables.Int64Col()
        loan_purpose_not_available_pct_of_upb = tables.Int32Col()
        weighted_average_original_cltv = tables.Int16Col()
        maximum_cltv_q4 = tables.Int16Col()
        third_quartile_cltv_q3 = tables.Int16Col()
        median_cltv_q2 = tables.Int16Col()
        first_quartile_cltv_q1 = tables.Int16Col()
        minimum_cltv_q0 = tables.Int16Col()
        weighted_average_original_loan_size = tables.Int64Col()
        look_back_period = tables.Int8Col()
        one_unit_number_of_loans = tables.Int32Col()
        one_unit_upb = tables.Int64Col()
        one_unit_pct_of_upb = tables.Int32Col()
        few_units_number_of_loans = tables.Int32Col()
        few_units_upb = tables.Int64Col()
        few_units_pct_of_upb = tables.Int32Col()
        ptna_number_of_loans = tables.Int32Col()
        ptna_upb = tables.Int64Col()
        ptna_pct_of_upb = tables.Int32Col()
        pool_upb = tables.Int64Col()
        as_of_date = tables.Time32Col()

    class MultiIssuers(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        issuer_number = tables.StringCol(4)
        issuer_name = tables.StringCol(40)
        number_of_loans = tables.Int32Col()
        issuers_upb = tables.Int64Col()
        issuers_pct_of_pool = tables.Int16Col()
        as_of_date = tables.Time32Col()

    class MSAs(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        issuer = tables.Int16Col()
        first_msa = tables.Int32Col()
        first_number_loans = tables.Int32Col()
        first_upb_loans = tables.Int64Col()
        first_pct_upb = tables.Int16Col()
        second_msa = tables.Int32Col()
        second_number_loans = tables.Int32Col()
        second_upb_loans = tables.Int64Col()
        second_pct_upb = tables.Int16Col()
        third_msa = tables.Int32Col()
        third_number_loans = tables.Int32Col()
        third_upb_loans = tables.Int64Col()
        third_pct_upb = tables.Int16Col()
        fourth_msa = tables.Int32Col()
        fourth_number_loans = tables.Int32Col()
        fourth_upb_loans = tables.Int64Col()
        fourth_pct_upb = tables.Int16Col()
        fifth_msa = tables.Int32Col()
        fifth_number_loans = tables.Int32Col()
        fifth_upb_loans = tables.Int64Col()
        fifth_pct_upb = tables.Int16Col()
        sixth_msa = tables.Int32Col()
        sixth_number_loans = tables.Int32Col()
        sixth_upb_loans = tables.Int64Col()
        sixth_pct_upb = tables.Int16Col()
        seventh_msa = tables.Int32Col()
        seventh_number_loans = tables.Int32Col()
        seventh_upb_loans = tables.Int64Col()
        seventh_pct_upb = tables.Int16Col()
        eighth_msa = tables.Int32Col()
        eighth_number_loans = tables.Int32Col()
        eighth_upb_loans = tables.Int64Col()
        eighth_pct_upb = tables.Int16Col()
        ninth_msa = tables.Int32Col()
        ninth_number_loans = tables.Int32Col()
        ninth_upb_loans = tables.Int64Col()
        ninth_pct_upb = tables.Int16Col()
        tenth_msa = tables.Int32Col()
        tenth_number_loans = tables.Int32Col()
        tenth_upb_loans = tables.Int64Col()
        tenth_pct_upb = tables.Int16Col()
        no_msa_number_loans = tables.Int32Col()
        no_msa_upb_loans = tables.Int64Col()
        no_msa_pct_upb = tables.Int16Col()
        as_of_date = tables.Time32Col()

    class Years(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        origin_yr_1 = tables.Int16Col()
        upb_foy_1 = tables.Int64Col()
        pct_upb_foy_1 = tables.Int16Col()
        num_loans_foy_1 = tables.Int32Col()
        pct_loans_foy_1 = tables.Int16Col()
        origin_yr_2 = tables.Int16Col()
        upb_foy_2 = tables.Int64Col()
        pct_upb_foy_2 = tables.Int16Col()
        num_loans_foy_2 = tables.Int32Col()
        pct_loans_foy_2 = tables.Int16Col()
        origin_yr_3 = tables.Int16Col()
        upb_foy_3 = tables.Int64Col()
        pct_upb_foy_3 = tables.Int16Col()
        num_loans_foy_3 = tables.Int32Col()
        pct_loans_foy_3 = tables.Int16Col()
        origin_yr_4 = tables.Int16Col()
        upb_foy_4 = tables.Int64Col()
        pct_upb_foy_4 = tables.Int16Col()
        num_loans_foy_4 = tables.Int32Col()
        pct_loans_foy_4 = tables.Int16Col()
        origin_yr_others = tables.StringCol(4)
        upb_foy_others = tables.Int64Col()
        pct_upb_foy_others = tables.Int16Col()
        num_loans_foy_others = tables.Int32Col()
        pct_loans_foy_others = tables.Int16Col()
        as_of_date = tables.Time32Col()

    class PreModifications(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        issuer = tables.Int16Col()
        avg_lad = tables.Int16Col()
        maximum_lad_q4 = tables.Int16Col()
        third_quartile_lad_q3 = tables.Int16Col()
        median_lad_q2 = tables.Int16Col()
        first_quartile_lad_q1 = tables.Int16Col()
        min_lad_q0 = tables.Int16Col()
        upb_for_premodified_loans = tables.Int64Col()
        pct_of_pool_upb = tables.Int16Col()
        num_loans = tables.Int32Col()
        pct_of_pool = tables.Int16Col()
        premodified_ols = tables.Int64Col()
        max_premodified_ols_q4 = tables.Int64Col()
        third_quartile_premodified_ols_q3 = tables.Int64Col()
        median_premodified_ols_q2 = tables.Int64Col()
        first_quartile_premodified_ols_q1 = tables.Int64Col()
        min_premodified_ols_q0 = tables.Int64Col()
        upb_premodified_opb = tables.Int64Col()
        pct_of_pool_upb_premodified_opb = tables.Int16Col()
        num_loans_premodified_opb = tables.Int32Col()
        pct_of_pool_premodified_opb = tables.Int16Col()
        as_of_date = tables.Time32Col()

    class Removals(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        issuer = tables.Int16Col()
        mortgagor_payoff_num_loans = tables.Int32Col()
        mortgagor_payoff_upb = tables.Int64Col()
        mortgagor_payoff_pct_upb = tables.Int64Col()
        repurchase_delinquent_loan_num_loans = tables.Int32Col()
        repurchase_delinquent_loan_upb = tables.Int64Col()
        repurchase_delinquent_loan_pct_upb = tables.Int64Col()
        foreclosure_claim_payment_num_loans = tables.Int32Col()
        foreclosure_claim_payment_upb = tables.Int64Col()
        foreclosure_claim_payment_pct_upb = tables.Int64Col()
        repurchase_loss_mitigation_num_loans = tables.Int32Col()
        repurchase_loss_mitigation_upb = tables.Int64Col()
        repurchase_loss_mitigation_pct_upb = tables.Int64Col()
        substitution_num_loans = tables.Int32Col()
        substitution_upb = tables.Int64Col()
        substitution_number_of_pct_upb = tables.Int64Col()
        other_removal_num_loans = tables.Int32Col()
        other_removal_upb = tables.Int64Col()
        other_removal_number_of_pct_upb = tables.Int64Col()
        as_of_date = tables.Time32Col()

    class States(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        state = tables.StringCol(2)
        current_security_balance_state = tables.Int64Col()
        balance_pct = tables.Int16Col()
        num_loans_state = tables.Int32Col()
        num_loans_pct = tables.Int16Col()
        total_loans = tables.Int32Col()
        original_balance_state = tables.Int64Col()
        as_of_date = tables.Time32Col()

    class Variouses(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.StringCol(1)
        pool_type = tables.StringCol(2)
        fha_pool_upb = tables.Int64Col()
        fha_upb_pct_total_pool = tables.Int16Col()
        fha_num_loans = tables.Int32Col()
        fha_num_loans_pct_total_loans = tables.Int16Col()
        fha_original_pool_balance = tables.Int64Col()
        va_pool_upb = tables.Int64Col()
        va_upb_pct_total_pool = tables.Int16Col()
        va_num_loans = tables.Int32Col()
        va_num_loans_pct_total_loans = tables.Int16Col()
        va_original_pool_balance = tables.Int64Col()
        rd_pool_upb = tables.Int64Col()
        rd_upb_pct_total_pool = tables.Int16Col()
        rd_num_loans = tables.Int32Col()
        rd_num_loans_pct_total_loans = tables.Int16Col()
        rd_original_pool_balance = tables.Int64Col()
        pih_pool_upb = tables.Int64Col()
        pih_upb_pct_total_pool = tables.Int16Col()
        pih_num_loans = tables.Int32Col()
        pih_num_loans_pct_total_loans = tables.Int16Col()
        pih_original_pool_balance = tables.Int64Col()
        num_loans_paid_off = tables.Int32Col()
        unpaid_principal_balance_of_loans_paid_off = tables.Int64Col()
        pct_upb_of_loans_paid_off = tables.Int16Col()
        number_of_repurchased_delinquent_loans = tables.Int32Col()
        upb_of_repurchased_delinquent_loans = tables.Int64Col()
        pct_upb_of_repurchased_delinquent_loans = tables.Int16Col()
        num_loans_foreclosed_with_claim_payment = tables.Int32Col()
        upb_of_loans_foreclosed_with_claim_payment = tables.Int64Col()
        pct_upb_of_loans_foreclosed_with_claim_payment = tables.Int16Col()
        number_of_repurchased_loss_mitigation_loans = tables.Int32Col()
        upb_of_repurchased_loss_mitigation_loans = tables.Int64Col()
        pct_upb_of_repurchased_loss_mitigation_loans = tables.Int16Col()
        number_of_repurchased_substitution_loans = tables.Int32Col()
        upb_of_repurchased_substitution_loans = tables.Int64Col()
        pct_upb_of_repurchased_substitution_loans = tables.Int16Col()
        number_of_other_removal_repurchased_loans = tables.Int32Col()
        upb_of_other_removal_repurchased_loans = tables.Int64Col()
        pct_upb_of_other_removal_repurchased_loans = tables.Int16Col()
        number_of_fha_buydown_loans = tables.Int32Col()
        upb_of_fha_buydown_loans = tables.Int64Col()
        pct_upb_of_fha_buydown_loans = tables.Int16Col()
        number_of_va_buydown_loans = tables.Int32Col()
        upb_of_va_buydown_loans = tables.Int64Col()
        pct_upb_of_va_buydown_loans = tables.Int16Col()
        num_loans_30_days_delinquent = tables.Int32Col()
        upb_of_loans_30_days_delinquent = tables.Int64Col()
        pct_upb_of_loans_30_days_delinquent = tables.Int16Col()
        num_loans_60_days_delinquent = tables.Int32Col()
        upb_of_loans_60_days_delinquent = tables.Int64Col()
        pct_upb_of_loans_60_days_delinquent = tables.Int16Col()
        num_loans_90_days_delinquent = tables.Int32Col()
        upb_of_loans_90_days_delinquent = tables.Int64Col()
        pct_upb_of_loans_90_days_delinquent = tables.Int16Col()
        fha_num_loans_30_days_delinquent = tables.Int32Col()
        fha_upb_of_loans_30_days_delinquent = tables.Int64Col()
        fha_pct_upb_of_loans_30_days_delinquent = tables.Int16Col()
        fha_num_loans_60_days_delinquent = tables.Int32Col()
        fha_upb_of_loans_60_days_delinquent = tables.Int64Col()
        fha_pct_upb_of_loans_60_days_delinquent = tables.Int16Col()
        fha_num_loans_90_days_delinquent = tables.Int32Col()
        fha_upb_of_loans_90_days_delinquent = tables.Int64Col()
        fha_pct_upb_of_loans_90_days_delinquent = tables.Int16Col()
        va_num_loans_30_days_delinquent = tables.Int32Col()
        va_upb_of_loans_30_days_delinquent = tables.Int64Col()
        va_pct_upb_of_loans_30_days_delinquent = tables.Int16Col()
        va_num_loans_60_days_delinquent = tables.Int32Col()
        va_upb_of_loans_60_days_delinquent = tables.Int64Col()
        va_pct_upb_of_loans_60_days_delinquent = tables.Int16Col()
        va_num_loans_90_days_delinquent = tables.Int32Col()
        va_upb_of_loans_90_days_delinquent = tables.Int64Col()
        va_pct_upb_of_loans_90_days_delinquent = tables.Int16Col()
        rd_num_loans_30_days_delinquent = tables.Int32Col()
        rd_upb_of_loans_30_days_delinquent = tables.Int64Col()
        rd_pct_upb_of_loans_30_days_delinquent = tables.Int16Col()
        rd_num_loans_60_days_delinquent = tables.Int32Col()
        rd_upb_of_loans_60_days_delinquent = tables.Int64Col()
        rd_pct_upb_of_loans_60_days_delinquent = tables.Int16Col()
        rd_num_loans_90_days_delinquent = tables.Int32Col()
        rd_upb_of_loans_90_days_delinquent = tables.Int64Col()
        rd_pct_upb_of_loans_90_days_delinquent = tables.Int16Col()
        pih_num_loans_30_days_delinquent = tables.Int32Col()
        pih_upb_of_loans_30_days_delinquent = tables.Int64Col()
        pih_pct_upb_of_loans_30_days_delinquent = tables.Int16Col()
        pih_num_loans_60_days_delinquent = tables.Int32Col()
        pih_upb_of_loans_60_days_delinquent = tables.Int64Col()
        pih_pct_upb_of_loans_60_days_delinquent = tables.Int16Col()
        pih_num_loans_90_days_delinquent = tables.Int32Col()
        pih_upb_of_loans_90_days_delinquent = tables.Int64Col()
        pih_pct_upb_of_loans_90_days_delinquent = tables.Int16Col()
        as_of_date = tables.Time32Col()

    class Supplementals(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        issuer = tables.Int16Col()
        weighted_average_credit_score = tables.Int16Col()
        maximum_credit_score_q4 = tables.Int16Col()
        third_quartile_credit_score_q3 = tables.Int16Col()
        median_credit_score_q2 = tables.Int16Col()
        first_quartile_credit_score_q1 = tables.Int16Col()
        minimum_credit_score_q0 = tables.Int16Col()
        credit_score_not_available_num_loans = tables.Int32Col()
        credit_score_not_available_upb = tables.Int64Col()
        credit_score_not_available_pct_upb = tables.Int16Col()
        weighted_average_debt_income_ratio = tables.Int16Col()
        maximum_debt_income_ratio_q4 = tables.Int16Col()
        third_quartile_debt_income_ratio_q3 = tables.Int16Col()
        median_debt_income_ratio_q2 = tables.Int16Col()
        first_quartile_debt_income_ratio_q1 = tables.Int16Col()
        minimum_debt_income_ratio_q0 = tables.Int16Col()
        debt_income_ratio_not_available_num_loans = tables.Int32Col()
        debt_income_ratio_not_available_upb = tables.Int64Col()
        debt_income_ratio_not_available_pct_upb = tables.Int16Col()
        down_payment_assistance_num_loans = tables.Int32Col()
        down_payment_assistance_upb = tables.Int64Col()
        down_payment_assistance_pct_upb = tables.Int16Col()
        without_payment_assistance_num_loans = tables.Int32Col()
        without_payment_assistance_upb = tables.Int64Col()
        without_payment_assistance_pct_upb = tables.Int16Col()
        fha_purchase_num_loans = tables.Int32Col()
        fha_purchase_upb = tables.Int64Col()
        fha_purchase_pct_upb = tables.Int16Col()
        fha_refinance_num_loans = tables.Int32Col()
        fha_refinance_upb = tables.Int64Col()
        fha_refinance_pct_upb = tables.Int16Col()
        fha_hamp_modified_num_loans = tables.Int32Col()
        fha_hamp_modified_upb = tables.Int64Col()
        fha_hamp_modified_pct_upb = tables.Int16Col()
        fha_nonhamp_modified_num_loans = tables.Int32Col()
        fha_nonhamp_modified_upb = tables.Int64Col()
        fha_nonhamp_modified_pct_upb = tables.Int16Col()
        fha_purpose_not_available_num_loans = tables.Int32Col()
        fha_purpose_not_available_upb = tables.Int64Col()
        fha_purpose_not_available_pct_upb = tables.Int16Col()
        va_purchase_num_loans = tables.Int32Col()
        va_purchase_upb = tables.Int64Col()
        va_purchase_pct_upb = tables.Int16Col()
        va_refinance_num_loans = tables.Int32Col()
        va_refinance_upb = tables.Int64Col()
        va_refinance_pct_upb = tables.Int16Col()
        va_hamp_modified_num_loans = tables.Int32Col()
        va_hamp_modified_upb = tables.Int64Col()
        va_hamp_modified_pct_upb = tables.Int16Col()
        va_nonhamp_modified_num_loans = tables.Int32Col()
        va_nonhamp_modified_upb = tables.Int64Col()
        va_nonhamp_modified_pct_upb = tables.Int16Col()
        va_purpose_not_available_num_loans = tables.Int32Col()
        va_purpose_not_available_upb = tables.Int64Col()
        va_purpose_not_available_pct_upb = tables.Int16Col()
        pih_purchase_num_loans = tables.Int32Col()
        pih_purchase_upb = tables.Int64Col()
        pih_purchase_pct_upb = tables.Int16Col()
        pih_refinance_num_loans = tables.Int32Col()
        pih_refinance_upb = tables.Int64Col()
        pih_refinance_pct_upb = tables.Int16Col()
        pih_hamp_modified_num_loans = tables.Int32Col()
        pih_hamp_modified_upb = tables.Int64Col()
        pih_hamp_modified_pct_upb = tables.Int16Col()
        pih_nonhamp_modified_num_loans = tables.Int32Col()
        pih_nonhamp_modified_upb = tables.Int64Col()
        pih_nonhamp_modified_pct_upb = tables.Int16Col()
        pih_purpose_not_available_num_loans = tables.Int32Col()
        pih_purpose_not_available_upb = tables.Int64Col()
        pih_purpose_not_available_pct_upb = tables.Int16Col()
        rd_purchase_num_loans = tables.Int32Col()
        rd_purchase_upb = tables.Int64Col()
        rd_purchase_pct_upb = tables.Int16Col()
        rd_refinance_num_loans = tables.Int32Col()
        rd_refinance_upb = tables.Int64Col()
        rd_refinance_pct_upb = tables.Int16Col()
        rd_hamp_modified_num_loans = tables.Int32Col()
        rd_hamp_modified_upb = tables.Int64Col()
        rd_hamp_modified_pct_upb = tables.Int16Col()
        rd_nonhamp_modified_num_loans = tables.Int32Col()
        rd_nonhamp_modified_upb = tables.Int64Col()
        rd_nonhamp_modified_pct_upb = tables.Int16Col()
        rd_purpose_not_available_num_loans = tables.Int32Col()
        rd_purpose_not_available_upb = tables.Int64Col()
        rd_purpose_not_available_pct_upb = tables.Int16Col()
        non_streamlined_refi_num_loans = tables.Int32Col()
        non_streamlined_refi_purchase_upb = tables.Int64Col()
        non_streamlined_refi_purchase_pct_upb = tables.Int16Col()
        cash_out_refi_num_loans = tables.Int32Col()
        cash_out_refi_upb = tables.Int64Col()
        cash_out_refi_pct_upb = tables.Int16Col()
        streamlined_refi_num_loans = tables.Int32Col()
        streamlined_refi_upb = tables.Int64Col()
        streamlined_refi_pct_upb = tables.Int16Col()
        fha_short_refinance_num_loans = tables.Int32Col()
        fha_short_refinance_upb = tables.Int64Col()
        fha_short_refinance_pct_upb = tables.Int16Col()
        refinance_type_not_available_num_loans = tables.Int32Col()
        refinance_type_not_available_upb = tables.Int64Col()
        refinance_type_not_available_pct_upb = tables.Int16Col()
        as_of_date = tables.Time32Col()

    class MultiIssuerDeliquencies(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        issuer = tables.Int16Col()
        num_loans_thirty_days_delinquent = tables.Int32Col()
        upb_thirty_days_delinquent = tables.Int64Col()
        pct_upb_thirty_days_delinquent = tables.Int16Col()
        num_loans_sixty_days_delinquent = tables.Int32Col()
        upb_sixty_days_delinquent = tables.Int64Col()
        pct_upb_sixty_days_delinquent = tables.Int16Col()
        num_loans_ninety_days_delinquent = tables.Int32Col()
        upb_ninety_days_delinquent = tables.Int64Col()
        pct_upb_ninety_days_delinquent = tables.Int16Col()
        fha_num_loans_thirty_days_delinquent = tables.Int32Col()
        fha_upb_thirty_days_delinquent = tables.Int64Col()
        fha_pct_upb_thirty_days_delinquent = tables.Int16Col()
        fha_num_loans_sixty_days_delinquent = tables.Int32Col()
        fha_upb_sixty_days_delinquent = tables.Int64Col()
        fha_pct_upb_sixty_days_delinquent = tables.Int16Col()
        fha_num_loans_ninety_days_delinquent = tables.Int32Col()
        fha_upb_ninety_days_delinquent = tables.Int64Col()
        fha_pct_upb_ninety_days_delinquent = tables.Int16Col()
        va_num_loans_thirty_days_delinquent = tables.Int32Col()
        va_upb_thirty_days_delinquent = tables.Int64Col()
        va_pct_upb_thirty_days_delinquent = tables.Int16Col()
        va_num_loans_sixty_days_delinquent = tables.Int32Col()
        va_upb_sixty_days_delinquent = tables.Int64Col()
        va_pct_upb_sixty_days_delinquent = tables.Int16Col()
        va_num_loans_ninety_days_delinquent = tables.Int32Col()
        va_upb_ninety_days_delinquent = tables.Int64Col()
        va_pct_upb_ninety_days_delinquent = tables.Int16Col()
        rd_num_loans_thirty_days_delinquent = tables.Int32Col()
        rd_upb_thirty_days_delinquent = tables.Int64Col()
        rd_pct_upb_thirty_days_delinquent = tables.Int16Col()
        rd_num_loans_sixty_days_delinquent = tables.Int32Col()
        rd_upb_sixty_days_delinquent = tables.Int64Col()
        rd_pct_upb_sixty_days_delinquent = tables.Int16Col()
        rd_num_loans_ninety_days_delinquent = tables.Int32Col()
        rd_upb_ninety_days_delinquent = tables.Int64Col()
        rd_pct_upb_ninety_days_delinquent = tables.Int16Col()
        pih_num_loans_thirty_days_delinquent = tables.Int32Col()
        pih_upb_thirty_days_delinquent = tables.Int64Col()
        pih_pct_upb_thirty_days_delinquent = tables.Int16Col()
        pih_num_loans_sixty_days_delinquent = tables.Int32Col()
        pih_upb_sixty_days_delinquent = tables.Int64Col()
        pih_pct_upb_sixty_days_delinquent = tables.Int16Col()
        pih_num_loans_ninety_days_delinquent = tables.Int32Col()
        pih_upb_ninety_days_delinquent = tables.Int64Col()
        pih_pct_upb_ninety_days_delinquent = tables.Int16Col()
        as_of_date = tables.Time32Col()

    class InsurancePremiums(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        issuer = tables.Int16Col()
        upfront_mip_100_num_loans = tables.Int32Col()
        upfront_mip_100_upb = tables.Int64Col()
        upfront_mip_100_pct_upb = tables.Int16Col()
        upfront_mip_125_num_loans = tables.Int32Col()
        upfront_mip_125_upb = tables.Int64Col()
        upfront_mip_125_pct_upb = tables.Int16Col()
        upfront_mip_150_num_loans = tables.Int32Col()
        upfront_mip_150_upb = tables.Int64Col()
        upfront_mip_150_pct_upb = tables.Int16Col()
        upfront_mip_175_num_loans = tables.Int32Col()
        upfront_mip_175_upb = tables.Int64Col()
        upfront_mip_175_pct_upb = tables.Int16Col()
        upfront_mip_200_num_loans = tables.Int32Col()
        upfront_mip_200_upb = tables.Int64Col()
        upfront_mip_200_pct_upb = tables.Int16Col()
        upfront_mip_225_num_loans = tables.Int32Col()
        upfront_mip_225_upb = tables.Int64Col()
        upfront_mip_225_pct_upb = tables.Int16Col()
        upfront_mip_NA_num_loans = tables.Int32Col()
        upfront_mip_NA_upb = tables.Int64Col()
        upfront_mip_NA_pct_upb = tables.Int16Col()
        annual_mip_25_num_loans = tables.Int32Col()
        annual_mip_25_upb = tables.Int64Col()
        annual_mip_25_pct_upb = tables.Int16Col()
        annual_mip_35_num_loans = tables.Int32Col()
        annual_mip_35_upb = tables.Int64Col()
        annual_mip_35_pct_upb = tables.Int16Col()
        annual_mip_50_num_loans = tables.Int32Col()
        annual_mip_50_upb = tables.Int64Col()
        annual_mip_50_pct_upb = tables.Int16Col()
        annual_mip_55_num_loans = tables.Int32Col()
        annual_mip_55_upb = tables.Int64Col()
        annual_mip_55_pct_upb = tables.Int16Col()
        annual_mip_60_num_loans = tables.Int32Col()
        annual_mip_60_upb = tables.Int64Col()
        annual_mip_60_pct_upb = tables.Int16Col()
        annual_mip_85_num_loans = tables.Int32Col()
        annual_mip_85_upb = tables.Int64Col()
        annual_mip_85_pct_upb = tables.Int16Col()
        annual_mip_90_num_loans = tables.Int32Col()
        annual_mip_90_upb = tables.Int64Col()
        annual_mip_90_pct_upb = tables.Int16Col()
        annual_mip_110_num_loans = tables.Int32Col()
        annual_mip_110_upb = tables.Int64Col()
        annual_mip_110_pct_upb = tables.Int16Col()
        annual_mip_115_num_loans = tables.Int32Col()
        annual_mip_115_upb = tables.Int64Col()
        annual_mip_115_pct_upb = tables.Int16Col()
        annual_mip_120_num_loans = tables.Int32Col()
        annual_mip_120_upb = tables.Int64Col()
        annual_mip_120_pct_upb = tables.Int16Col()
        annual_mip_125_num_loans = tables.Int32Col()
        annual_mip_125_upb = tables.Int64Col()
        annual_mip_125_pct_upb = tables.Int16Col()
        annual_mip_145_num_loans = tables.Int32Col()
        annual_mip_145_upb = tables.Int64Col()
        annual_mip_145_pct_upb = tables.Int16Col()
        annual_mip_150_num_loans = tables.Int32Col()
        annual_mip_150_upb = tables.Int64Col()
        annual_mip_150_pct_upb = tables.Int16Col()
        annual_mip_NA_num_loans = tables.Int32Col()
        annual_mip_NA_upb = tables.Int64Col()
        annual_mip_NA_pct_upb = tables.Int16Col()
        first_time_homebuyer_num_loans = tables.Int32Col()
        first_time_homebuyer_upb = tables.Int64Col()
        first_time_homebuyer_pct_upb = tables.Int16Col()
        not_first_time_homebuyer_num_loans = tables.Int32Col()
        not_first_time_homebuyer_upb = tables.Int64Col()
        not_first_time_homebuyer_pct_upb = tables.Int16Col()
        first_time_homebuyer_NA_num_loans = tables.Int32Col()
        first_time_homebuyer_NA_upb = tables.Int64Col()
        first_time_homebuyer_NA_pct_upb = tables.Int16Col()
        broker_num_loans = tables.Int32Col()
        broker_upb = tables.Int64Col()
        broker_pct_upb = tables.Int16Col()
        correspondent_num_loans = tables.Int32Col()
        correspondent_upb = tables.Int64Col()
        correspondent_pct_upb = tables.Int16Col()
        retail_num_loans = tables.Int32Col()
        retail_upb = tables.Int64Col()
        retail_pct_upb = tables.Int16Col()
        origination_type_NA_num_loans = tables.Int32Col()
        origination_type_NA_upb = tables.Int64Col()
        origination_type_NA_pct_upb = tables.Int16Col()
        upfront_mip_000_num_loans = tables.Int32Col()
        upfront_mip_000_upb = tables.Int64Col()
        upfront_mip_000_pct_upb = tables.Int16Col()
        mip_001_num_loans = tables.Int32Col()
        mip_001_upb = tables.Int64Col()
        mip_001_pct_upb = tables.Int16Col()
        mip_300_num_loans = tables.Int32Col()
        mip_300_upb = tables.Int64Col()
        mip_300_pct_upb = tables.Int16Col()
        mip_380_num_loans = tables.Int32Col()
        mip_380_upb = tables.Int64Col()
        mip_380_pct_upb = tables.Int16Col()
        annual_mip_000_num_loans = tables.Int32Col()
        annual_mip_000_upb = tables.Int64Col()
        annual_mip_000_pct_upb = tables.Int16Col()
        mip_other_num_loans = tables.Int32Col()
        mip_other_upb = tables.Int64Col()
        mip_other_pct_upb = tables.Int16Col()
        mip_45_num_loans = tables.Int32Col()
        mip_45_upb = tables.Int64Col()
        mip_45_pct_upb = tables.Int16Col()
        mip_70_num_loans = tables.Int32Col()
        mip_70_upb = tables.Int64Col()
        mip_70_pct_upb = tables.Int16Col()
        mip_95_num_loans = tables.Int32Col()
        mip_95_upb = tables.Int64Col()
        mip_95_pct_upb = tables.Int16Col()
        mip_130_num_loans = tables.Int32Col()
        mip_130_upb = tables.Int64Col()
        mip_130_pct_upb = tables.Int16Col()
        mip_135_num_loans = tables.Int32Col()
        mip_135_upb = tables.Int64Col()
        mip_135_pct_upb = tables.Int16Col()
        mip_155_num_loans = tables.Int32Col()
        mip_155_upb = tables.Int64Col()
        mip_155_pct_upb = tables.Int16Col()
        mip_50_num_loans = tables.Int32Col()
        mip_50_upb = tables.Int64Col()
        mip_50_pct_upb = tables.Int16Col()
        mip_240_num_loans = tables.Int32Col()
        mip_240_upb = tables.Int64Col()
        mip_240_pct_upb = tables.Int16Col()
        mip_250_num_loans = tables.Int32Col()
        mip_250_upb = tables.Int64Col()
        mip_250_pct_upb = tables.Int16Col()
        mip_75_num_loans = tables.Int32Col()
        mip_75_upb = tables.Int64Col()
        mip_75_pct_upb = tables.Int16Col()
        mip_80_num_loans = tables.Int32Col()
        mip_80_upb = tables.Int64Col()
        mip_80_pct_upb = tables.Int16Col()
        mip_100_num_loans = tables.Int32Col()
        mip_100_upb = tables.Int64Col()
        mip_100_pct_upb = tables.Int16Col()
        mip_105_num_loans = tables.Int32Col()
        mip_105_upb = tables.Int64Col()
        mip_105_pct_upb = tables.Int16Col()
        as_of_date = tables.Time32Col()

    class TransferActivities(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_number = tables.StringCol(6)
        pool_indicator = tables.EnumCol(["X","C","M"],"X",base='int8')
        pool_type = tables.StringCol(2)
        pool_issue_date = tables.Time32Col()
        #transfer_type = tables.EnumCol(["blank","piit","regular"],"blank",base='int8')
        transfer_type = tables.Int8Col()
        selling_issuer = tables.Int16Col()
        buying_issuer = tables.Int16Col()
        num_loans_transferred = tables.Int32Col()
        upb_transferred = tables.Int64Col()
        as_of_date = tables.Time32Col()

    class CandidatePools(tables.IsDescription): #List of pools that we care about.
        cusip = tables.StringCol(9)
        pool_type = tables.StringCol(3)

    class CPR_3M(tables.IsDescription): #Pre-calculated 3M CPR by cusip, coupon, and vintage
        cusip = tables.StringCol(9)
        vintage = tables.Int16Col()
        security_interest_rate = tables.Int32Col()
        date = tables.Time32Col()
        cpr_3m = tables.FloatCol()


class GNM_II_LL_Mixin(object):
    """File defs and h5 table defs for GNM II LoanLevel files"""

    #I.e., enums for which the file stores an index value, not the enum string
    DIRECT_ENUMS = ['loan_purpose', 'refinance_type', 'origination_type', 'removal_reason']
    LOAN_DEF = dict(pool_id = (1,7), dsn = (7,17), issuer_id = (17,21), agency = (21,22), loan_purpose = (22,23),
            refinance_type = (23,24), first_payment_date = (24,32), maturity_date = (32,40), loan_interest_rate = (40,45),
            original_principal_balance = (45,56), upb_at_issuance = (56,67), upb = (67,78), original_loan_term = (78,81),
            loan_age = (81,84), remaining_loan_term = (84,87), months_delinquent = (87,88), months_prepaid = (88,89),
            loan_gross_margin = (89,93), ltv = (93,98), total_debt_expense_ratio = (103,108),
            credit_score = (108,111), down_payment_assistance = (111,112), buy_down_status = (112,113), upfront_mip = (113,118),
            annual_mip = (118,123), number_of_borrowers = (123,124), first_time = (124,125), property_type = (125,126),
            state = (126,128), origination_type = (133,134), current_month_liquidation = (134,135),
            removal_reason = (135,136), as_of_date = (136,142), loan_origination_date=(142,150), seller_issuer_id=(150,154))
    NOT_USED_LOAN_DEF = dict(msa = (128,133), combined_ltv = (98,103))
    POOL_DEF = dict(cusip = (1,10), pool_id = (10,16), issue_type = (16,17), pool_type = (17,19), pool_issue_date = (19,27),
            issuer_id = (27,30), as_of_date = (31,37))
    FILE_DEF = dict(filename = (1,23), file_number = (23,26), correction_flag = (26,27),
                    as_of_date = (27,33), generated_date = (33,41))

    class Pools(tables.IsDescription):
        cusip = tables.StringCol(9)
        pool_id = tables.StringCol(6)
        issue_type = tables.EnumCol(['X','C','M'],'X',base='int8')
        pool_type = tables.StringCol(3)
        pool_issue_date = tables.Time32Col()
        issuer_id = tables.Int16Col()
        as_of_date = tables.Time32Col()

    class Files(tables.IsDescription):
        filename = tables.StringCol(22)
        file_number = tables.Int16Col()
        correction_flag = tables.EnumCol(["N","Y"],"N",base='int8')
        as_of_date = tables.Time32Col()
        generated_date = tables.Time32Col()

    class Loans(tables.IsDescription):
        pool_id = tables.StringCol(6)
        dsn = tables.Int32Col() #Disclosure Sequence Number
        issuer_id = tables.Int16Col()
        agency = tables.EnumCol(list("FVRN"),"F",base='int8') # F = FHA, V = VA, R = Rural, N = Native American
        loan_purpose = tables.EnumCol({'Purchase':1,'Refinance':2,'HAMPmod':3,'nonHAMPmod':4,'blank':0},
                                      'Purchase',base='int8') 
        refinance_type = tables.EnumCol({'Normal':1,'CashOut':2,'Streamlined':3,'blank':0},
                                        'Normal',base='int8')
        first_payment_date = tables.Time32Col() #First scheduled installment
        maturity_date = tables.Time32Col()
        loan_interest_rate = tables.FloatCol()
        original_principal_balance = tables.Int32Col() #to nearest thousand
        upb_at_issuance = tables.Int32Col() # Unpaid principal balance at issuance
        upb = tables.Int32Col() #blank for first 6 months
        original_loan_term = tables.Int16Col()  # Total # of months in loan
        loan_age = tables.Int16Col() # # of months since start of loan
        remaining_loan_term = tables.Int16Col() # Remaining # of months in loan
        months_delinquent = tables.Int8Col() # right-censored months' delinquent
        months_prepaid = tables.Int8Col() # right-censored months' prepaid
        loan_gross_margin = tables.Int32Col() # ARM loans only
        ltv = tables.Int16Col() # loan-to-value ratio in bps < 10% or > 125% is blank
        total_debt_expense_ratio = tables.Int16Col() # <10% or >65% is blank (!)
        credit_score = tables.Int16Col() # < 300 or > 850 is blank
        down_payment_assistance = tables.EnumCol(["N","Y"],"N",base='int8')
        buy_down_status = tables.EnumCol(["N","Y"],"N",base='int8') #lower rate at first
        upfront_mip = tables.Int32Col() #insurance premium rate
        annual_mip = tables.Int32Col()
        number_of_borrowers = tables.Int8Col()
        first_time = tables.EnumCol(["N","Y"],"Y",base='int8')
        property_type = tables.Int8Col() # # of living units
        state = tables.StringCol(2)
        origination_type = tables.EnumCol({'Broker':1,'Correspondent':2,'Retail':3,'blank':0},
                                          'Broker',base='int8')
        current_month_liquidation = tables.EnumCol(["N","Y"],"N",base='int8')
        removal_reason = tables.EnumCol({'Payoff':1, 'Repurchase of delinquent loan':2,
                                         'Foreclosure with claim payment':3, 'Loss mitigation':4,
                                         'Substitution':5, 'Other':6,'blank':0},"Payoff",base='int8')
        as_of_date = tables.Time32Col()
        loan_origination_date = tables.Time32Col()
        seller_issuer_id = tables.Int16Col()
        #msa = tables.Int32Col() #metropolitan statistical area (blank on these)
        #combined_ltv = tables.Int16Col() # combined loan-to-value (?) always blank
